version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - aws ecr get-login-password | docker login --username AWS --password-stdin <account>.dkr.ecr.<region>.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t mern-app .

  post_build:
    commands:
      - docker tag mern-app:latest <ECR-URI>:latest
      - docker push <ECR-URI>:latest

artifacts:
  files:
    - '**/*'
