version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - aws ecr get-login-password | docker login --username AWS --password-stdin 365647375826.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t mern-app .

  post_build:
    commands:
      - docker tag mern-app:latest 365647375826.dkr.ecr.ap-south-1.amazonaws.com/mern-app-repo:latest
      - docker push 365647375826.dkr.ecr.ap-south-1.amazonaws.com/mern-app-repo:latest

artifacts:
  files:
    - '**/*'
